services:
  frontend:
    image: fe-booking:1.0.0
    container_name: fe-booking
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge